name: Deploy on Main Push/PR

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  checkout:
    runs-on: ubuntu-latest
    outputs:
      ssh-key: ${{ steps.set-key.outputs.ssh-key }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Save SSH Key to Output
        id: set-key
        run: echo "::set-output name=ssh-key::${{ secrets.SSH_PRIVATE_KEY }}"

  prepare:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan "${{ secrets.SERVER_IP }}" >> ~/.ssh/known_hosts

  deploy:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: SSH into server and deploy
        run: |
          ssh -i ~/.ssh/id_rsa user@your.server.ip << 'EOF'
            cd /home/deployer/project-track/server
            git pull
            npm run build
            pm2 remove 0 || true
            ${{ secrets.START_CMD }}
          EOF
