name: Deploy on Main Push/PR
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Pre-Prod     # Environment containing your secrets and variables
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          # write your private key directly from the secret
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          # add the server to known_hosts
          ssh-keyscan "${{ secrets.SERVER_IP }}" >> ~/.ssh/known_hosts
      
      - name: SSH into server and deploy
        run: |
          ssh -i ~/.ssh/id_rsa deployer@${{ secrets.SERVER_IP }} << EOF
            cd "${{ vars.BACKEND_PATH }}"
            git pull
            npm i 
            npm run build
            pm2 remove 0 || true
            ${{ vars.START_CMD }}
          EOF
